name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore "WebShopAPI/WebShopAPI.sln"
    - name: Build "WebShopAPI/WebShopAPI.sln" --no-restore
      run: dotnet build "WebShopAPI/WebShopAPI.sln" --no-restore
    - name: Test
      run: dotnet test "WebShopAPI/unitTests/unitTests.csproj" --no-build --verbosity normal

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/web-shop-api:${{ github.sha }} .

    - name: Push Docker image to DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/web-shop-api:${{ github.sha }}
