name: Tauri

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
            pkg-config \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libjavascriptcoregtk-4.0-dev \
            libjavascriptcoregtk-4.1-dev \
            libsoup-3.0-dev

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Set PKG_CONFIG_PATH
      run: |
        export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: |
          ManagerWebShop/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('ManagerWebShop/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      working-directory: ../S3DB01-Martijn-Verhappen-Individual-Project/ManagerWebShop
      run: npm install

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        rustup update
        rustup target add x86_64-unknown-linux-gnu

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Build the Tauri app
      working-directory: ../S3DB01-Martijn-Verhappen-Individual-Project/ManagerWebShop
      run: npm run tauri build

    - name: Run Unit Tests
      run: npm test -- src/__tests__

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ManagerWebShop-build
        path: src-tauri/target/release/bundle
