name: Tauri

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install necessary dependencies for GDK
      - name: Install GDK and other dependencies
        run: |
          sudo apt update
          sudo apt install -y pkg-config libgtk-3-dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ../S3DB01-Martijn-Verhappen-Individual-Project/ManagerWebShop
        run: npm install

      - name: Build the Tauri app
        working-directory: ../S3DB01-Martijn-Verhappen-Individual-Project/ManagerWebShop
        run: npm run tauri build

      - name: Run Unit Tests
        run: npm test -- src/__tests__

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ManagerWebShop-build
          path: src-tauri/target/release/bundle
